build: off
cache: "c:\\sr -> appveyor.yml"

test_script:
- set HLINT_ARGUMENTS=src
- ps: Invoke-Expression (Invoke-WebRequest 'https://raw.githubusercontent.com/ndmitchell/neil/master/appveyor.ps1')
- set UNIPLATE_VERBOSE=-1
- stack exec -- hlint test
- stack exec -- hlint src
