# Because hsdev hasn't upgraded we need our own Snapshot, see:
# * https://github.com/commercialhaskell/stackage/issues/4673
# * https://github.com/commercialhaskell/stackage/issues/4731
resolver: nightly-2019-08-07 # Don't roll to an 8.8.1 or 8.8.2 resolver because of the Windows linker bug
packages:
  - .
extra-deps:
  - ghc-lib-parser-8.8.3.20200224
  - ghc-lib-parser-ex-8.8.5.3
# To test hlint against experimental builds of ghc-lib-parser-ex,
# modify extra-deps like this:
#  - archive: /users/shaynefletcher/project/ghc-lib-parser-ex.git/ghc-lib-parser-ex-8.8.5.3.tar.gz
  - haskell-src-exts-1.23.0
  - extra-1.6.19
ghc-options: {"$locals": -ddump-to-file -ddump-hi}
# dependency (rather ghc will). Enabling this stanza forces both hlint
# and ghc-lib-parser-ex to depend on ghc-lib-parser int his case.
# flags:
#   hlint:
#     ghc-lib: true
#   ghc-lib-parser-ex:
#     ghc-lib: true
