resolver: nightly-2020-03-14
packages:
  - .
extra-deps:
  - ghc-lib-parser-8.8.3.20200224
  - ghc-lib-parser-ex-8.8.5.6
# To test hlint against experimental builds of ghc-lib-parser-ex,
# modify extra-deps like this:
#  - archive: /users/shaynefletcher/project/ghc-lib-parser-ex.git/ghc-lib-parser-ex-8.8.5.3.tar.gz
  - haskell-src-exts-1.23.0
  - extra-1.7.1
ghc-options: {"$locals": -ddump-to-file -ddump-hi -Werror=unused-imports -Werror=unused-top-binds}
# Enabling this stanza forces both hlint and ghc-lib-parser-ex to
# depend on ghc-lib-parser.
# flags:
#   hlint:
#     ghc-lib: true
#   ghc-lib-parser-ex:
#     ghc-lib: true
